#!/usr/bin/env python3
"""Cuts the gacha HUD sheet (assets/ui/source/gacha_sheet2.png) into ONE
atlas, assets/ui/gacha_atlas.webp, and writes the CSS that addresses it
into client/css/style.css between the "gacha atlas" markers.

    python3 tools/slice-gacha.py [preview.png]

One file instead of fifty: the page loads it once, and the demo build stays
under its file-count limit. In the page every piece is an element with the
class `ga ga-<name>`; its size is the piece's own size times --s (default .5),
so one variable scales a piece without any maths at the call site.
"""
import os
import re
import sys
import numpy as np
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), '..')
SHEET = np.array(Image.open(os.path.join(ROOT, 'assets/ui/source/gacha_sheet2.png')).convert('RGBA'))
CSS = os.path.join(ROOT, 'client/css/style.css')


def crop(box):
    x0, y0, x1, y1 = box
    a = SHEET[y0:y1, x0:x1].copy()
    al = a[:, :, 3].astype(np.float32)
    al = np.where(al < 40, 0, np.clip(al * 255 / 250, 0, 255))   # the blurred backdrop goes
    a[:, :, 3] = al.astype(np.uint8)
    return a


def hole(a, inset):
    """Clear the middle of a frame so what sits behind it shows."""
    l, t, r, b = inset
    h, w = a.shape[:2]
    a[t:h - b, l:w - r, 3] = 0
    return a


def smear(a, box, src):
    x0, y0, x1, y1 = box
    a[y0:y1, x0:x1] = a[y0:y1, src:src + 1]
    return a


P = {}
P['title'] = crop((12, 3, 419, 131))
for i, (y0, y1) in enumerate([(136, 232), (237, 329), (332, 418), (424, 511), (515, 600), (606, 689), (695, 785)]):
    P[f'banner{i}'] = crop((13, y0 - 1, 343, y1 + 1))
P['ticket'] = crop((1392, 13, 1442, 57))
P['frame'] = hole(crop((353, 117, 885, 373)), (30, 44, 30, 36))
P['rateup'] = hole(crop((900, 121, 1320, 373)), (34, 70, 34, 30))
P['detail'] = crop((1331, 112, 1529, 384))
g = crop((361, 377, 911, 419))
P['gauge_pity'] = smear(g, (76, 10, 492, 33), 470)            # the fill and its "120 / 200" wiped
g = crop((941, 377, 1339, 419))
P['gauge_ssr'] = smear(g, (124, 10, 360, 33), 356)            # likewise "80 / 100"
for name, box in {'draw1': (358, 428, 586, 531), 'draw10': (592, 428, 823, 531), 'drawfree': (829, 422, 1081, 531),
                  'rates': (1096, 431, 1240, 483), 'history': (1247, 431, 1382, 483), 'skip': (1389, 432, 1522, 485),
                  'g_R': (358, 545, 457, 597), 'g_SR': (463, 545, 559, 597), 'g_SSR': (566, 545, 663, 598),
                  'g_UR': (671, 545, 772, 599), 'g_LR': (781, 544, 899, 599), 'tag_rateup': (908, 545, 1066, 602),
                  't_new': (355, 612, 475, 670), 't_pickup': (489, 614, 598, 668), 't_rateup': (609, 611, 716, 668),
                  't_guarantee': (727, 607, 888, 676), 't_limited': (897, 610, 1035, 669),
                  'congrats': (1225, 615, 1524, 704),
                  'r_R': (352, 691, 446, 787), 'r_SR': (454, 688, 552, 789), 'r_SSR': (560, 688, 662, 791),
                  'r_UR': (671, 683, 770, 789), 'r_LR': (781, 684, 883, 791), 'r_X': (893, 678, 1001, 797),
                  'portal': (1020, 664, 1216, 835), 'ring_blue': (998, 844, 1125, 898),
                  'ring_gold': (1137, 840, 1255, 908), 'ring_pink': (1270, 841, 1379, 892),
                  'ann_SSR': (18, 919, 388, 1012), 'ann_UR': (407, 919, 761, 1014),
                  'ann_LR': (780, 919, 1165, 1012), 'ann_item': (1187, 917, 1506, 999)}.items():
    P[name] = crop(box)
for k in ('r_R', 'r_SR', 'r_SSR', 'r_UR', 'r_LR', 'r_X'):
    h, w = P[k].shape[:2]
    P[k] = hole(P[k], (int(w * .14),) * 4)

# shelf-pack into one atlas, tallest first
W, PAD = 1100, 2
order = sorted(P, key=lambda k: -P[k].shape[0])
x = y = shelf = 0
at = {}
for k in order:
    h, w = P[k].shape[:2]
    if x + w > W:
        x, y, shelf = 0, y + shelf + PAD, 0
    at[k] = (x, y, w, h)
    x += w + PAD
    shelf = max(shelf, h)
H = y + shelf
atlas = np.zeros((H, W, 4), np.uint8)
for k, (x, y, w, h) in at.items():
    atlas[y:y + h, x:x + w] = P[k]
Image.fromarray(atlas).save(os.path.join(ROOT, 'assets/ui/gacha_atlas.webp'), 'WEBP', quality=88, method=6)

rules = [f'/* gacha atlas: generated by tools/slice-gacha.py - do not edit by hand */',
         f'.ga {{ display: block; flex: none; background: url(../../assets/ui/gacha_atlas.webp) no-repeat;'
         f' width: calc(var(--w) * var(--s, .5) * 1px); height: calc(var(--h) * var(--s, .5) * 1px);'
         f' background-size: calc({W} * var(--s, .5) * 1px) calc({H} * var(--s, .5) * 1px);'
         f' background-position: calc(var(--x) * var(--s, .5) * -1px) calc(var(--y) * var(--s, .5) * -1px); }}']
for k in sorted(at):
    x, y, w, h = at[k]
    rules.append(f'.ga-{k} {{ --x: {x}; --y: {y}; --w: {w}; --h: {h}; }}')
rules.append('/* end gacha atlas */')
block = '\n'.join(rules)
css = open(CSS).read()
if '/* gacha atlas:' in css:
    css = re.sub(r'/\* gacha atlas:.*?/\* end gacha atlas \*/', lambda _: block, css, flags=re.S)
else:
    css += '\n' + block + '\n'
open(CSS, 'w').write(css)

if len(sys.argv) > 1:
    bg = Image.new('RGBA', (W, H), (30, 90, 40, 255))
    bg.alpha_composite(Image.fromarray(atlas))
    bg.convert('RGB').save(sys.argv[1])
print(len(P), 'pieces,', f'{W}x{H}')
