#!/usr/bin/env python3
"""The ground Emberhold's buildings, stalls and posts stand on, as solids.

    python3 tools/solids-town.py [overlay.png]

A body walks through a house's roof and under its eaves - a roof is up in
the air - but not through its walls. These are the walls' and stalls' feet,
the lamp posts' and banners' bases (POSTS in build-town.py) and the
fountain's basin, in px of the 1x picture (1536x1024, 17.07px a tile).
Writes shared/data/emberhold-solids.js: [x, y, w, h] in tiles, for
shared/solids.js.
"""
import importlib.util
import os
import sys

from PIL import Image, ImageDraw

ROOT = os.path.join(os.path.dirname(__file__), '..')
spec = importlib.util.spec_from_file_location('bt', os.path.join(ROOT, 'tools/build-town.py'))
bt = importlib.util.module_from_spec(spec)
spec.loader.exec_module(bt)

TILE_PX = 1536 / 90
# x0, y0, x1, y1: where each building meets the ground, on the 1x picture
FOOTPRINTS = {
    'nw_house': (318, 175, 478, 292),
    'w_house': (388, 380, 572, 462),
    'ne_row_blue': (995, 200, 1115, 296),
    'ne_row_red': (1128, 200, 1270, 296),
    'e_hall': (968, 405, 1160, 484),
    'sw_cottages': (200, 628, 342, 694),
    'sw_house': (300, 770, 405, 874),
    's_row_left': (485, 770, 575, 884),
    's_row_right': (578, 765, 690, 884),
    's_house': (878, 818, 988, 890),
    'chapel': (1082, 700, 1310, 834),
    'e_edge': (1442, 120, 1536, 214),
    # (the house cut off at the west edge stands over the only way down to the
    # west dock, so it keeps no footprint)
    # the market stalls: their counters
    'stall_n_left': (600, 305, 676, 345),
    'stall_n_right': (866, 305, 944, 345),
    'stall_w_market': (440, 560, 570, 603),
    'stall_e_market': (980, 572, 1112, 606),
    'stall_se': (995, 676, 1078, 714),
    # the fountain's basin, all of it: it is low, so it is all ground
    'fountain': (688, 440, 856, 552),
}
POST_HALF, POST_DEPTH = 7, 9


def main(overlay=None):
    rects = list(FOOTPRINTS.values())
    rects += [(x - POST_HALF, y - POST_DEPTH, x + POST_HALF, y + 1) for x, y, _ in bt.POSTS]
    t = lambda v: round(v / TILE_PX, 2)
    with open(os.path.join(ROOT, 'shared/data/emberhold-solids.js'), 'w') as fp:
        fp.write('// Generated by tools/solids-town.py - do not edit by hand.\n')
        fp.write('// What stands on the ground in Emberhold: [x, y, w, h] in tiles (see shared/solids.js).\n')
        fp.write('export const EMBERHOLD_SOLIDS = [\n')
        for x0, y0, x1, y1 in rects:
            fp.write(f'  [{t(x0)}, {t(y0)}, {t(x1 - x0)}, {t(y1 - y0)}],\n')
        fp.write('];\n')
    if overlay:
        im = Image.open(os.path.join(ROOT, bt.TOWN)).convert('RGBA')
        lay = Image.new('RGBA', im.size)
        d = ImageDraw.Draw(lay)
        for r in rects:
            d.rectangle(r, fill=(255, 0, 0, 110), outline=(255, 255, 0, 255))
        im.alpha_composite(lay)
        im.convert('RGB').save(overlay)
    print(len(rects), 'solids')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else None)
