#!/usr/bin/env python3
"""Trace which tiles of a painted field can be walked on.

    python3 tools/trace-field.py greenmire [overlay.png]

A painted map is one picture; the game still needs to know where a character
may stand. The picture is split into the map's tile grid and each pixel is
sorted by colour: the dirt paths, the open grass and the wooden stairs and
bridges are ground; tree canopy, water, the grey cliff faces and boulders are
not. A tile is blocked when too little of it is ground. Pockets of ground no
path reaches (a clearing walled in by trees, the little islands) are closed
too, so nothing can be stranded there.

Writes shared/data/<id>-obstacles.js (one string per row, '#' blocked) and
assets/maps/<id>.webp (the picture the game draws).
"""
import os
import sys
from collections import deque

import cv2
import numpy as np
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), '..')

FIELDS = {
    'greenmire': {
        'src': 'assets/maps/source/greenmire.png',
        'cols': 60, 'rows': 40,
        # where a character walks in from; everything not joined to it is closed
        'seed': (30, 3),
        # Decided by eye where colour cannot tell, as [x, y, w, h] in tiles:
        # the stairs and bridges (plank shadows read as cliff), and the paths
        # that pass through a tree's shade.
        'force_open': [
            [29, 0, 2, 4],     # north stairs to the top edge
            [5, 3, 2, 3],      # stairs, north-west ledge
            [13, 5, 3, 3],     # bridge over the west stream
            [7, 13, 3, 4],     # stairs down, west
            [43, 3, 2, 4],     # stairs, north-east ledge
            [55, 6, 2, 4],     # stairs, east ledge
            [46, 13, 4, 2],    # bridge over the east stream
            [30, 13, 2, 3],    # stairs, middle mound
            [53, 16, 2, 3],    # stairs down to the south-east pool
            [7, 19, 2, 4],     # bridge, west river
            [19, 25, 2, 4],    # stairs down, south-west
            [45, 24, 2, 4],    # stairs down, south-east
            [32, 30, 2, 3],    # stairs to the south bridge
            [32, 33, 3, 4],    # the south bridge, and the path below it
            [9, 16, 4, 2],     # the path west from the middle, under the trees
            [19, 23, 3, 3],    # down to the south-west stairs
            [7, 6, 3, 3],      # the north-west corner, to the bridge
            [58, 9, 2, 3],     # the east path, out to the edge
            [50, 31, 8, 2],    # the south-east clearing past the pond (the warp to Ashfen)
        ],
        'force_block': [],
    },
}


def classify(rgb):
    """Per pixel: 1 ground, 0 blocked."""
    img = cv2.GaussianBlur(rgb, (0, 0), 1.6)
    hsv = cv2.cvtColor(img, cv2.COLOR_RGB2HSV).astype(np.int32)
    h, s, v = hsv[..., 0] * 2, hsv[..., 1], hsv[..., 2]
    R, G, B = [img[..., i].astype(np.int32) for i in range(3)]
    dirt = (h >= 22) & (h <= 50) & (v >= 150) & (s >= 60)
    grass = (h > 50) & (h <= 95) & (v >= 150) & (s >= 90)
    wood = (h >= 14) & (h < 40) & (v >= 110) & (v < 225) & (s >= 70) & (R - B > 60)
    water = (B > R + 30) & (B > G - 10)
    grey = (s < 70) & (v < 170)
    dark = v < 120
    ground = (dirt | grass | wood) & ~water & ~grey & ~dark
    return ground.astype(np.float32)


def main(key, overlay=None):
    cfg = FIELDS[key]
    rgb = np.array(Image.open(os.path.join(ROOT, cfg['src'])).convert('RGB'))
    H, W = rgb.shape[:2]
    cols, rows = cfg['cols'], cfg['rows']
    g = classify(rgb)
    share = cv2.resize(g, (cols, rows), interpolation=cv2.INTER_AREA)
    # the middle of a tile is where the feet are; weigh it over the corners
    core = np.zeros((rows, cols), np.float32)
    tw, th = W / cols, H / rows
    for y in range(rows):
        for x in range(cols):
            y0, y1 = int((y + 0.2) * th), int((y + 0.8) * th)
            x0, x1 = int((x + 0.2) * tw), int((x + 0.8) * tw)
            core[y, x] = g[y0:y1, x0:x1].mean()
    open_ = (share * 0.4 + core * 0.6) >= 0.55
    for x, y, w, h in cfg['force_open']:
        open_[y:y + h, x:x + w] = True
    for x, y, w, h in cfg['force_block']:
        open_[y:y + h, x:x + w] = False
    # keep only the ground joined to where people arrive
    sx, sy = cfg['seed']
    seen = np.zeros_like(open_)
    q = deque([(sx, sy)])
    seen[sy, sx] = True
    while q:
        x, y = q.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < cols and 0 <= ny < rows and open_[ny, nx] and not seen[ny, nx]:
                seen[ny, nx] = True
                q.append((nx, ny))
    lines = [''.join('.' if seen[y, x] else '#' for x in range(cols)) for y in range(rows)]
    const = key.upper() + '_OBSTACLES'
    with open(os.path.join(ROOT, f'shared/data/{key}-obstacles.js'), 'w') as fp:
        fp.write(f'// Generated by tools/trace-field.py from {cfg["src"]} - do not edit by hand.\n')
        fp.write("// One string per map row; '#' is a tile nobody may stand on.\n")
        fp.write(f'export const {const} = [\n')
        for ln in lines:
            fp.write(f"  '{ln}',\n")
        fp.write('];\n')
    Image.fromarray(rgb).save(os.path.join(ROOT, f'assets/maps/{key}.webp'), 'WEBP', quality=92, method=6)
    if overlay:
        ov = Image.fromarray(rgb).resize((W * 2, H * 2), Image.LANCZOS).convert('RGBA')
        lay = np.zeros((rows, cols, 4), np.uint8)
        lay[~open_] = (0, 0, 0, 150)               # blocked by what is painted there
        lay[open_ & ~seen] = (255, 0, 0, 130)      # ground, but cut off from the rest
        lay = Image.fromarray(lay).resize((W * 2, H * 2), Image.NEAREST)
        ov.alpha_composite(lay)
        from PIL import ImageDraw
        d = ImageDraw.Draw(ov)
        for x in range(cols + 1):
            X = round(x * tw * 2)
            d.line([(X, 0), (X, H * 2)], fill=(255, 255, 255, 90) if x % 5 else (255, 255, 0, 200))
            if x % 5 == 0 and x < cols:
                d.text((X + 2, 2), str(x), fill=(255, 255, 0))
        for y in range(rows + 1):
            Y = round(y * th * 2)
            d.line([(0, Y), (W * 2, Y)], fill=(255, 255, 255, 90) if y % 5 else (255, 255, 0, 200))
            if y % 5 == 0 and y < rows:
                d.text((2, Y + 2), str(y), fill=(255, 255, 0))
        ov.convert('RGB').save(overlay)
    print(key, int(seen.sum()), 'open tiles of', cols * rows)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
