#!/usr/bin/env python3
"""Trace where a character may stand in Emberhold.

    python3 tools/trace-town.py [overlay.png]

Two pictures of the same town, the same size and in register:
  assets/maps/source/emberhold2/layout.png  the walk plan: paving, stairs and
                                            bridges between walls, lawns and water
  assets/maps/source/emberhold3/full.png    the painted town on that plan, with
                                            houses and stalls on the lawns
A tile is open where the plan has paving (or is one of the stairs and joins
listed below, whose step shadows read as walls) and the painting still has
paving there - a house that spills over the plan's path closes it. The
fountain's basin is closed by hand. Only ground joined to the square is kept.
Writes shared/data/emberhold-obstacles.js (90x60, '#' blocked).
"""
import os
import sys
from collections import deque

import cv2
import numpy as np
from PIL import Image, ImageDraw

ROOT = os.path.join(os.path.dirname(__file__), '..')
PLAN = 'assets/maps/source/emberhold2/layout.png'
TOWN = 'assets/maps/source/emberhold3/full.png'
COLS, ROWS = 90, 60
SEED = (45, 34)                        # the square below the fountain
# x, y, w, h in tiles: stairs, the bridge heads and the castle gate
FORCE_OPEN = [
    (31, 10, 4, 4), (13, 23, 4, 5), (75, 5, 4, 4), (55, 10, 3, 4), (74, 22, 4, 5), (9, 33, 2, 3),
    (22, 32, 4, 4), (42, 38, 6, 5), (64, 51, 5, 9), (42, 49, 6, 5), (65, 32, 4, 4), (13, 4, 4, 5),
    (43, 3, 5, 4), (9, 29, 4, 3), (78, 29, 5, 3), (58, 43, 6, 5),
    (56, 42, 8, 1), (57, 40, 2, 3), (34, 20, 4, 3),     # paving the shade of a stall or roof hides
]
FORCE_BLOCK = [(40, 25, 10, 8)]
# the lamp posts and banners: the tile each stands on (see POSTS in build-town.py)
import importlib.util
_spec = importlib.util.spec_from_file_location('build_town', os.path.join(os.path.dirname(__file__), 'build-town.py'))
_bt = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_bt)
POSTS = _bt.POSTS        # the fountain basin (its statue rises over the path behind: see build-town.py)


def tile_share(mask, inset=(0.2, 0.8, 0.3, 0.95)):
    """How much of each tile's middle (where the feet are) the mask covers."""
    H, W = mask.shape
    tw, th = W / COLS, H / ROWS
    out = np.zeros((ROWS, COLS))
    x0, x1, y0, y1 = inset
    for y in range(ROWS):
        for x in range(COLS):
            out[y, x] = mask[int((y + y0) * th):int((y + y1) * th), int((x + x0) * tw):int((x + x1) * tw)].mean()
    return out


def main(overlay=None):
    plan = np.array(Image.open(os.path.join(ROOT, PLAN)).convert('RGB'))
    town = np.array(Image.open(os.path.join(ROOT, TOWN)).convert('RGB'))
    # the plan: pale paving without the dark lines of a wall edge, or wood
    hsv = cv2.cvtColor(cv2.GaussianBlur(plan, (0, 0), 1), cv2.COLOR_RGB2HSV).astype(int)
    h, s, v = hsv[..., 0] * 2, hsv[..., 1], hsv[..., 2]
    lawn = (h > 45) & (h < 100) & (s > 110)
    wood = (h >= 15) & (h <= 40) & (s > 120) & (v > 90) & ~lawn
    pave = (s < 95) & (v >= 135) & (v >= 115)
    dark = v < 115
    plan_open = ((tile_share(pave, (0.15, 0.85, 0.15, 0.85)) > 0.72) & (tile_share(dark, (0.15, 0.85, 0.15, 0.85)) < 0.06)) \
        | (tile_share(wood, (0.15, 0.85, 0.15, 0.85)) > 0.5)
    # the painting: still paving
    hsv = cv2.cvtColor(cv2.GaussianBlur(town, (0, 0), 1.2), cv2.COLOR_RGB2HSV).astype(int)
    h, s, v = hsv[..., 0] * 2, hsv[..., 1], hsv[..., 2]
    town_pave = (s < 90) & (v >= 150) & ((h <= 45) | (s < 30))
    open_ = plan_open & (tile_share(town_pave) > 0.55)
    for x, y, w, hh in FORCE_OPEN:
        open_[y:y + hh, x:x + w] = True
    for x, y, w, hh in FORCE_BLOCK:
        open_[y:y + hh, x:x + w] = False
    W, H = town.shape[1], town.shape[0]
    for px, py, _ in POSTS:
        tx, ty = int(px / (W / COLS)), min(ROWS - 1, int((py - 3) / (H / ROWS)))
        open_[ty, tx] = False
    sx, sy = SEED
    seen = np.zeros_like(open_)
    seen[sy, sx] = True
    q = deque([(sx, sy)])
    while q:
        x, y = q.popleft()
        for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
            nx, ny = x + dx, y + dy
            if 0 <= nx < COLS and 0 <= ny < ROWS and open_[ny, nx] and not seen[ny, nx]:
                seen[ny, nx] = True
                q.append((nx, ny))
    with open(os.path.join(ROOT, 'shared/data/emberhold-obstacles.js'), 'w') as fp:
        fp.write(f'// Generated by tools/trace-town.py from {PLAN} and {TOWN} - do not edit by hand.\n')
        fp.write("// One string per map row; '#' is a tile nobody may stand on.\n")
        fp.write('export const EMBERHOLD_OBSTACLES = [\n')
        for y in range(ROWS):
            fp.write("  '" + ''.join('.' if seen[y, x] else '#' for x in range(COLS)) + "',\n")
        fp.write('];\n')
    if overlay:
        H, W = town.shape[:2]
        tw, th = W / COLS, H / ROWS
        ov = Image.fromarray(town).convert('RGBA')
        lay = np.zeros((ROWS, COLS, 4), np.uint8)
        lay[~seen] = (0, 0, 0, 150)
        lay[seen] = (80, 255, 140, 50)
        lay[open_ & ~seen] = (255, 0, 0, 140)
        ov.alpha_composite(Image.fromarray(lay).resize((W, H), Image.NEAREST))
        d = ImageDraw.Draw(ov)
        for x in range(0, COLS + 1, 5):
            d.line([(x * tw, 0), (x * tw, H)], fill=(255, 255, 0, 140))
            d.text((x * tw + 2, 2), str(x), fill=(255, 255, 0))
        for y in range(0, ROWS + 1, 5):
            d.line([(0, y * th), (W, y * th)], fill=(255, 255, 0, 140))
            d.text((2, y * th + 2), str(y), fill=(255, 255, 0))
        ov.convert('RGB').save(overlay)
    print('emberhold', int(seen.sum()), 'open tiles of', COLS * ROWS)


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else None)
